### ISSUE TITLE
Kali Linux error LibraryNotFoundError: Error detecting the version of libcrypto

### ISSUE THREAD

**Issue by chikamobina** [skelsec/pypykatz#136]
└─$ pypykatz                                                  
Traceback (most recent call last):
  File "/usr/local/bin/pypykatz", line 33, in <module>
    sys.exit(load_entry_point('pypykatz==0.6.9', 'console_scripts', 'pypykatz')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pypykatz-0.6.9-py3.11.egg/pypykatz/__main__.py", line 17, in main
  File "/usr/local/lib/python3.11/dist-packages/pypykatz-0.6.9-py3.11.egg/pypykatz/kerberos/cmdhelper.py", line 19, in <module>
  File "/usr/local/lib/python3.11/dist-packages/pypykatz-0.6.9-py3.11.egg/pypykatz/kerberos/kerberos.py", line 7, in <module>
  File "/home/kali/.local/lib/python3.11/site-packages/minikerberos/security.py", line 11, in <module>
    from minikerberos.aioclient import AIOKerberosClient
  File "/home/kali/.local/lib/python3.11/site-packages/minikerberos/aioclient.py", line 31, in <module>
    from minikerberos.common.creds import KerberosCredential
  File "/home/kali/.local/lib/python3.11/site-packages/minikerberos/common/creds.py", line 24, in <module>
    from oscrypto.asymmetric import rsa_pkcs1v15_sign, load_private_key
  File "/usr/local/lib/python3.11/dist-packages/oscrypto-1.3.0-py3.11.egg/oscrypto/asymmetric.py", line 19, in <module>
    from ._asymmetric import _unwrap_private_key_info
  File "/usr/local/lib/python3.11/dist-packages/oscrypto-1.3.0-py3.11.egg/oscrypto/_asymmetric.py", line 27, in <module>
    from .kdf import pbkdf1, pbkdf2, pkcs12_kdf
  File "/usr/local/lib/python3.11/dist-packages/oscrypto-1.3.0-py3.11.egg/oscrypto/kdf.py", line 9, in <module>
    from .util import rand_bytes
  File "/usr/local/lib/python3.11/dist-packages/oscrypto-1.3.0-py3.11.egg/oscrypto/util.py", line 14, in <module>
    from ._openssl.util import rand_bytes
  File "/usr/local/lib/python3.11/dist-packages/oscrypto-1.3.0-py3.11.egg/oscrypto/_openssl/util.py", line 6, in <module>
    from ._libcrypto import libcrypto, libcrypto_version_info, handle_openssl_error
  File "/usr/local/lib/python3.11/dist-packages/oscrypto-1.3.0-py3.11.egg/oscrypto/_openssl/_libcrypto.py", line 9, in <module>
    from ._libcrypto_cffi import (
  File "/usr/local/lib/python3.11/dist-packages/oscrypto-1.3.0-py3.11.egg/oscrypto/_openssl/_libcrypto_cffi.py", line 44, in <module>
    raise LibraryNotFoundError('Error detecting the version of libcrypto')
oscrypto.errors.LibraryNotFoundError: Error detecting the version of libcrypto

What doesn’t work for me is the version installed via apt, not the version installed via pip, nothing at all. Please help me solve this problem.

**Comment by skelsec** [comment]
The issue you're seeing is that `oscrypto` has some weird error on Kali. To fix it you can update `oscrypto` by downloading it from github [here](https://github.com/wbond/oscrypto/tree/master) and install it.

**Comment by chikamobina** [comment]
Installed it, now it gives this error. I installed all the dependencies.

Traceback (most recent call last):
  File "/usr/local/bin/pypykatz", line 33, in <module>
    sys.exit(load_entry_point('pypykatz==0.6.9', 'console_scripts', 'pypykatz')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pypykatz-0.6.9-py3.11.egg/pypykatz/__main__.py", line 17, in main
  File "/usr/local/lib/python3.11/dist-packages/pypykatz-0.6.9-py3.11.egg/pypykatz/kerberos/cmdhelper.py", line 19, in <module>
  File "/usr/local/lib/python3.11/dist-packages/pypykatz-0.6.9-py3.11.egg/pypykatz/kerberos/kerberos.py", line 7, in <module>
ImportError: cannot import name 'krb5userenum' from 'minikerberos.security' (/home/kali/.local/lib/python3.11/site-packages/minikerberos/security.py)

**Comment by chikamobina** [comment]
Can you please tell me? How to solve this now? Thanks a lot

**Comment by chikamobina** [comment]
It seems to me that everyone who uses Kali is now faced with this, because all my friends have the same thing. Same errors

**Comment by chikamobina** [comment]
https://github.com/skelsec/pypykatz/issues/117 If this doesn't help, I tried setting 0.3.5

**Comment by iozicbeb** [comment]
This worked for me, first uninstall: `python -m pip uninstall oscrypto -y`, then install this version: `python -m pip install --force-reinstall https://github.com/wbond/oscrypto/archive/d5f3437ed24257895ae1edd9e503cfb352e635a8.zip`

**Comment by chikamobina** [comment]
> This worked for me, first uninstall: `python -m pip uninstall oscrypto -y`, then install this version: `python -m pip install --force-reinstall https://github.com/wbond/oscrypto/archive/d5f3437ed24257895ae1edd9e503cfb352e635a8.zip`

Traceback (most recent call last):
  File "/usr/local/bin/pypykatz", line 33, in <module>
    sys.exit(load_entry_point('pypykatz==0.6.9', 'console_scripts', 'pypykatz')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pypykatz-0.6.9-py3.11.egg/pypykatz/__main__.py", line 17, in main
  File "/usr/local/lib/python3.11/dist-packages/pypykatz-0.6.9-py3.11.egg/pypykatz/kerberos/cmdhelper.py", line 19, in <module>
  File "/usr/local/lib/python3.11/dist-packages/pypykatz-0.6.9-py3.11.egg/pypykatz/kerberos/kerberos.py", line 7, in <module>
ImportError: cannot import name 'krb5userenum' from 'minikerberos.security' (/home/kali/.local/lib/python3.11/site-packages/minikerberos/security.py)

**Comment by chikamobina** [comment]
I fixed it, for some reason I had 2 versions of minikerberos. I installed the latest one and removed the old one.

**Comment by 5h4rknet** [comment]
This issue should probably be reopened since it still exists in the currently released version of oscrypto (1.3.0): https://github.com/wbond/oscrypto/issues/78

This will continue to break pypykatz installs relying on the oscrypto pypi package for anyone using an openssl version where the major/minor/patch versions contain multiple digits, such as 3.0.10. There is currently no estimate for when this will be fixed upstream.

**Comment by AdrianVollmer** [comment]
This is an issue of the minikerberos dependency, also from @skelsec. The oscrypto maintainer is dragging his feet a bit (completely understandable for a hobby project), but would it be feasible to switch to the better maintained `cryptography` package? Lots of packages are depending on minikerberos which are now effectively broken.
